### ISSUE TITLE
autoAdjustHeight not updating when inner page size chanes

### ISSUE THREAD

**Issue by spike83** [techlab/SmartWizard#23] opened 2017-04-21 08:44 UTC
I have some forms inside the wizzard pages which can add some validation messages. A validation message is a span element, which normally is hidden. So when the validation hint is showing up the inner page becomes higher. In this case the smartWizzard is not updating the height and is truncating some content on bottom of the form.

Is there a way triggering _fixHeight function in such cases?

autoAdjustHeight was suggesting to me some automatic adjustment event after the initial load of the page:
Shouldn't the wizzard listen on size changes of the selPage and adjust it's height?

I can try to reporduce it in some plnker. Do you have a template for that?

**Comment by techlab** [comment] 2017-04-24 06:21
Hi, 
The issue is fixed on [v4.2.2](https://github.com/techlab/SmartWizard/releases/tag/v4.2.2)
It is a css change 
on `.sw-main .sw-container` removed the `overflow: hidden;`.
Also on JS file
`_fixHeight` function sets `min-height` instead of `height`

Thank you for reporting 👍

**Closed by techlab** 2017-04-24 06:21 UTC

**Comment by spike83** [comment] 2017-04-24 09:17
Thx. It works like a charm
