### ISSUE TITLE
After Ajax Contents loaded not working bootstrap selectpicker

### ISSUE THREAD

**Issue by trevi35** [techlab/SmartWizard#41] opened 2017-11-03 08:39 UTC
when I set `<select class="form-control selectpicker">` the select form is not visible

**Comment by techlab** [comment] 2018-03-11 17:18
It may be an issue with the selectpicker plugin or your implementation. Please include an example if you still have the problem. Closing the issue now, please reopen if you still think the issue is with SmartWizard. Thanks

**Closed by techlab** 2018-03-11 17:18 UTC
