### ISSUE TITLE
TypeError: btnGroupExtra is null

### ISSUE THREAD

**Issue by vaamyob** [techlab/SmartWizard#45] opened 2018-01-26 20:12 UTC
Steps to recreate:
```javascript
<script>
    $(document).ready(function() {
        $('#smartwizard').smartWizard({
            theme: "dots",
            toolbarSettings: {
                toolbarPosition: "both"
            }
        });
    });
</script>
```

**Comment by techlab** [comment] 2018-03-11 19:12
The issue is fixed in the latest release [v4.3.1](https://github.com/techlab/SmartWizard/releases/tag/v4.3.1). Thank you for reporting the issue.

**Closed by techlab** 2018-03-11 19:12 UTC
